#ifndef FLASHMEMORYLAYOUT_H_
#define FLASHMEMORYLAYOUT_H_

// The following must be consistent with linker script and datasheet:
#define FLASH_MEMORY_INFO_SIZE 128    // 128 bytes per information memory segment
#define FLASH_MEMORY_INFO_A    0x1980 // Information memory segment A address
#define FLASH_MEMORY_INFO_B    0x1900 // Information memory segment B address
#define FLASH_MEMORY_INFO_C    0x1880 // Information memory segment C address
#define FLASH_MEMORY_INFO_D    0x1800 // Information memory segment D address

#define FLASH_MEMORY_SIZE_INT16	2
#define FLASH_MEMORY_SIZE_FLOAT	4


/* 		Information Memory Segment A */

// Magic number at start indicating available values in information memory segments
#define FLASH_MEMORY_INFO_A_MAGIC      "DEADBEEF";
#define FLASH_MEMORY_INFO_A_SIZE_MAGIC 8

// Device name and length of name
#define FLASH_MEMORY_INFO_A_OFFSET_NAME        FLASH_MEMORY_INFO_A_SIZE_MAGIC
#define FLASH_MEMORY_INFO_A_SIZE_NAME          32
#define FLASH_MEMORY_INFO_A_OFFSET_NAME_LENGTH (FLASH_MEMORY_INFO_A_OFFSET_NAME + FLASH_MEMORY_INFO_A_SIZE_NAME + 1) // + '\0'
#define FLASH_MEMORY_INFO_A_SIZE_NAME_LENGTH   1

// Bluetooth bond information: Remote address and link key
#define FLASH_MEMORY_INFO_A_OFFSET_REMOTE_ADDR (FLASH_MEMORY_INFO_A_OFFSET_NAME_LENGTH + FLASH_MEMORY_INFO_A_SIZE_NAME_LENGTH)
#define FLASH_MEMORY_INFO_A_SIZE_REMOTE_ADDR   6
#define FLASH_MEMORY_INFO_A_OFFSET_LINK_KEY    (FLASH_MEMORY_INFO_A_OFFSET_REMOTE_ADDR + FLASH_MEMORY_INFO_A_SIZE_REMOTE_ADDR)
#define FLASH_MEMORY_INFO_A_SIZE_LINK_KEY      16


/* 		Information Memory Segment B, C and D
 * Contain MARG calibration data.
 * Must be consistent with Calibration class/struct.
 * Write has_inverted_placement bool as 2 bytes to fix access alignment of
 * following data.
 * Each MARG calibration data MUST start at the beginning of its own segment.
 */

// Hand MARG
#define FLASH_MEMORY_INFO_B_H_OFFSET_INV   0
#define FLASH_MEMORY_INFO_B_H_OFFSET_GOX   (FLASH_MEMORY_INFO_B_H_OFFSET_INV   + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_B_H_OFFSET_GOY   (FLASH_MEMORY_INFO_B_H_OFFSET_GOX   + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_B_H_OFFSET_GOZ   (FLASH_MEMORY_INFO_B_H_OFFSET_GOY   + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_B_H_OFFSET_GSX   (FLASH_MEMORY_INFO_B_H_OFFSET_GOZ   + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_B_H_OFFSET_GSY   (FLASH_MEMORY_INFO_B_H_OFFSET_GSX   + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_GSZ   (FLASH_MEMORY_INFO_B_H_OFFSET_GSY   + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_AOX   (FLASH_MEMORY_INFO_B_H_OFFSET_GSZ   + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_AOY   (FLASH_MEMORY_INFO_B_H_OFFSET_AOX   + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_B_H_OFFSET_AOZ   (FLASH_MEMORY_INFO_B_H_OFFSET_AOY   + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_B_H_OFFSET_ASX   (FLASH_MEMORY_INFO_B_H_OFFSET_AOZ   + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_B_H_OFFSET_ASY   (FLASH_MEMORY_INFO_B_H_OFFSET_ASX   + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_ASZ   (FLASH_MEMORY_INFO_B_H_OFFSET_ASY   + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MOX   (FLASH_MEMORY_INFO_B_H_OFFSET_ASZ   + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MOY   (FLASH_MEMORY_INFO_B_H_OFFSET_MOX   + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MOZ   (FLASH_MEMORY_INFO_B_H_OFFSET_MOY   + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MR00  (FLASH_MEMORY_INFO_B_H_OFFSET_MOZ   + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MR01  (FLASH_MEMORY_INFO_B_H_OFFSET_MR00  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MR02  (FLASH_MEMORY_INFO_B_H_OFFSET_MR01  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MR10  (FLASH_MEMORY_INFO_B_H_OFFSET_MR02  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MR11  (FLASH_MEMORY_INFO_B_H_OFFSET_MR10  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MR12  (FLASH_MEMORY_INFO_B_H_OFFSET_MR11  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MR20  (FLASH_MEMORY_INFO_B_H_OFFSET_MR12  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MR21  (FLASH_MEMORY_INFO_B_H_OFFSET_MR20  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_MR22  (FLASH_MEMORY_INFO_B_H_OFFSET_MR21  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_B_H_OFFSET_TEMP  (FLASH_MEMORY_INFO_B_H_OFFSET_MR22  + FLASH_MEMORY_SIZE_FLOAT)

// Forearm MARG
#define FLASH_MEMORY_INFO_C_LA_OFFSET_INV  0
#define FLASH_MEMORY_INFO_C_LA_OFFSET_GOX  (FLASH_MEMORY_INFO_C_LA_OFFSET_INV  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_GOY  (FLASH_MEMORY_INFO_C_LA_OFFSET_GOX  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_GOZ  (FLASH_MEMORY_INFO_C_LA_OFFSET_GOY  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_GSX  (FLASH_MEMORY_INFO_C_LA_OFFSET_GOZ  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_GSY  (FLASH_MEMORY_INFO_C_LA_OFFSET_GSX  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_GSZ  (FLASH_MEMORY_INFO_C_LA_OFFSET_GSY  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_AOX  (FLASH_MEMORY_INFO_C_LA_OFFSET_GSZ  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_AOY  (FLASH_MEMORY_INFO_C_LA_OFFSET_AOX  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_AOZ  (FLASH_MEMORY_INFO_C_LA_OFFSET_AOY  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_ASX  (FLASH_MEMORY_INFO_C_LA_OFFSET_AOZ  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_ASY  (FLASH_MEMORY_INFO_C_LA_OFFSET_ASX  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_ASZ  (FLASH_MEMORY_INFO_C_LA_OFFSET_ASY  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MOX  (FLASH_MEMORY_INFO_C_LA_OFFSET_ASZ  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MOY  (FLASH_MEMORY_INFO_C_LA_OFFSET_MOX  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MOZ  (FLASH_MEMORY_INFO_C_LA_OFFSET_MOY  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MR00 (FLASH_MEMORY_INFO_C_LA_OFFSET_MOZ  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MR01 (FLASH_MEMORY_INFO_C_LA_OFFSET_MR00 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MR02 (FLASH_MEMORY_INFO_C_LA_OFFSET_MR01 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MR10 (FLASH_MEMORY_INFO_C_LA_OFFSET_MR02 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MR11 (FLASH_MEMORY_INFO_C_LA_OFFSET_MR10 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MR12 (FLASH_MEMORY_INFO_C_LA_OFFSET_MR11 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MR20 (FLASH_MEMORY_INFO_C_LA_OFFSET_MR12 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MR21 (FLASH_MEMORY_INFO_C_LA_OFFSET_MR20 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_MR22 (FLASH_MEMORY_INFO_C_LA_OFFSET_MR21 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_C_LA_OFFSET_TEMP (FLASH_MEMORY_INFO_C_LA_OFFSET_MR22 + FLASH_MEMORY_SIZE_FLOAT)

// Upper arm MARG
#define FLASH_MEMORY_INFO_D_UA_OFFSET_INV  0
#define FLASH_MEMORY_INFO_D_UA_OFFSET_GOX  (FLASH_MEMORY_INFO_D_UA_OFFSET_INV  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_GOY  (FLASH_MEMORY_INFO_D_UA_OFFSET_GOX  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_GOZ  (FLASH_MEMORY_INFO_D_UA_OFFSET_GOY  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_GSX  (FLASH_MEMORY_INFO_D_UA_OFFSET_GOZ  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_GSY  (FLASH_MEMORY_INFO_D_UA_OFFSET_GSX  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_GSZ  (FLASH_MEMORY_INFO_D_UA_OFFSET_GSY  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_AOX  (FLASH_MEMORY_INFO_D_UA_OFFSET_GSZ  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_AOY  (FLASH_MEMORY_INFO_D_UA_OFFSET_AOX  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_AOZ  (FLASH_MEMORY_INFO_D_UA_OFFSET_AOY  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_ASX  (FLASH_MEMORY_INFO_D_UA_OFFSET_AOZ  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_ASY  (FLASH_MEMORY_INFO_D_UA_OFFSET_ASX  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_ASZ  (FLASH_MEMORY_INFO_D_UA_OFFSET_ASY  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MOX  (FLASH_MEMORY_INFO_D_UA_OFFSET_ASZ  + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MOY  (FLASH_MEMORY_INFO_D_UA_OFFSET_MOX  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MOZ  (FLASH_MEMORY_INFO_D_UA_OFFSET_MOY  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MR00 (FLASH_MEMORY_INFO_D_UA_OFFSET_MOZ  + FLASH_MEMORY_SIZE_INT16)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MR01 (FLASH_MEMORY_INFO_D_UA_OFFSET_MR00 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MR02 (FLASH_MEMORY_INFO_D_UA_OFFSET_MR01 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MR10 (FLASH_MEMORY_INFO_D_UA_OFFSET_MR02 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MR11 (FLASH_MEMORY_INFO_D_UA_OFFSET_MR10 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MR12 (FLASH_MEMORY_INFO_D_UA_OFFSET_MR11 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MR20 (FLASH_MEMORY_INFO_D_UA_OFFSET_MR12 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MR21 (FLASH_MEMORY_INFO_D_UA_OFFSET_MR20 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_MR22 (FLASH_MEMORY_INFO_D_UA_OFFSET_MR21 + FLASH_MEMORY_SIZE_FLOAT)
#define FLASH_MEMORY_INFO_D_UA_OFFSET_TEMP (FLASH_MEMORY_INFO_D_UA_OFFSET_MR22 + FLASH_MEMORY_SIZE_FLOAT)


/* Size checks */
#define FLASH_MEMORY_INFO_A_LAST_OFFSET FLASH_MEMORY_INFO_A_OFFSET_LINK_KEY
#define FLASH_MEMORY_INFO_A_LAST_SIZE   FLASH_MEMORY_INFO_A_SIZE_LINK_KEY
#define FLASH_MEMORY_INFO_B_LAST_OFFSET FLASH_MEMORY_INFO_B_H_OFFSET_TEMP
#define FLASH_MEMORY_INFO_B_LAST_SIZE   FLASH_MEMORY_SIZE_INT16
#define FLASH_MEMORY_INFO_C_LAST_OFFSET FLASH_MEMORY_INFO_C_LA_OFFSET_TEMP
#define FLASH_MEMORY_INFO_C_LAST_SIZE   FLASH_MEMORY_SIZE_INT16
#define FLASH_MEMORY_INFO_D_LAST_OFFSET FLASH_MEMORY_INFO_D_UA_OFFSET_TEMP
#define FLASH_MEMORY_INFO_D_LAST_SIZE   FLASH_MEMORY_SIZE_INT16

#define FLASH_MEMORY_INFO_A_USED        (FLASH_MEMORY_INFO_A_LAST_OFFSET + FLASH_MEMORY_INFO_A_LAST_SIZE)
#define FLASH_MEMORY_INFO_B_USED        (FLASH_MEMORY_INFO_B_LAST_OFFSET + FLASH_MEMORY_INFO_B_LAST_SIZE)
#define FLASH_MEMORY_INFO_C_USED        (FLASH_MEMORY_INFO_C_LAST_OFFSET + FLASH_MEMORY_INFO_C_LAST_SIZE)
#define FLASH_MEMORY_INFO_D_USED        (FLASH_MEMORY_INFO_D_LAST_OFFSET + FLASH_MEMORY_INFO_D_LAST_SIZE)
#if (FLASH_MEMORY_INFO_A_USED > FLASH_MEMORY_INFO_SIZE)
#error Flash information memory segment A overflow!
#endif
#if (FLASH_MEMORY_INFO_B_USED > FLASH_MEMORY_INFO_SIZE)
#error Flash information memory segment B overflow!
#endif
#if (FLASH_MEMORY_INFO_C_USED > FLASH_MEMORY_INFO_SIZE)
#error Flash information memory segment C overflow!
#endif
#if (FLASH_MEMORY_INFO_D_USED > FLASH_MEMORY_INFO_SIZE)
#error Flash information memory segment D overflow!
#endif

#endif /* FLASHMEMORYLAYOUT_H_ */
